export const futbolQuestions = [
    { question: "La selección argentina ganó el Mundial en 1978 y 1986.", answer: true },
    { question: "Lionel Messi es el máximo goleador histórico de la selección argentina.", answer: true },
    { question: "River Plate tiene más títulos nacionales que Boca Juniors.", answer: false },
    { question: "Argentina nunca ganó la Copa Confederaciones.", answer: false },
    { question: "El Superclásico es entre Racing y Independiente.", answer: false },
    { question: "Diego Maradona fue goleador en cinco campeonatos de la liga local.", answer: true },
    { question: "El club Quilmes fue fundado en el año 1901.", answer: false },
    { question: "El fútbol argentino se afilió a la FIFA en 1912.", answer: true },
    { question: "La Copa América la ganó Argentina 16 veces.", answer: true },
    { question: "Argentina ganó los Juegos Olímpicos de fútbol en Atenas 2004.", answer: true },
    { question: "La selección argentina nunca fue subcampeona del Mundial.", answer: false },
    { question: "El primer torneo de liga en Argentina fue en 1891.", answer: true },
    { question: "Boca Juniors solo tiene un título de Copa Libertadores.", answer: false },
    { question: "Arsenio Erico es el máximo goleador histórico del profesionalismo argentino.", answer: true },
    { question: "El apellido Gatti corresponde a un arquero mítico argentino.", answer: true },
    { question: "Argentina inventó la pelota moderna de fútbol en 1931.", answer: true },
    { question: "El gol más rápido argentino en Primera fue en 5 segundos.", answer: false },
    { question: "Maximiliano Susán hizo doce goles en un partido en 1909.", answer: true },
    { question: "River Plate nunca ganó una Copa Libertadores.", answer: false },
    { question: "Maradona jugó profesionalmente solo en Boca Juniors.", answer: false },
    { question: "Argentina tiene la mayor cantidad de convocatorias a la Copa América.", answer: false },
    { question: "La liga argentina es una de las más antiguas del mundo.", answer: true },
    { question: "Domingo Tarascone tuvo promedio de gol >2 en Olímpicos 1928.", answer: true },
    { question: "El Superclásico se considera el más intenso del mundo.", answer: true },
    { question: "Franco De Cicco escribió trivias sobre fútbol argentino.", answer: true },
    { question: "La Selección volvió a ganar el Mundial 2026 en Argentina.", answer: false },
    { question: "Racing Club se fundó antes que River Plate.", answer: true },
    { question: "Daniel Passarella fue uno de los defensores más goleadores.", answer: true },
    { question: "En Argentina no se celebra la Fiesta Nacional de la Pelota de Fútbol.", answer: false },
    { question: "El paí­s con más mundiales es Brasil, no Argentina.", answer: true },
];

export const monumentQuestions = [
  { question: "El Obelisco se encuentra en Buenos Aires.", answer: true },
  { question: "El Monumento a la Bandera está en San Juan.", answer: false },
  { question: "La Casa Histórica de Tucumán está en Tucumán.", answer: true },
  { question: "Francisco Salamone diseñó edificios comunales en Buenos Aires.", answer: true },
  { question: "El Teatro Colón está en Córdoba.", answer: false },
  { question: "Plaza de Mayo es donde se encuentra la Catedral Metropolitana.", answer: true },
  { question: "El Palacio Barolo está en Rosario.", answer: false },
  { question: "La Pirámide de Mayo está en Plaza de Mayo.", answer: true },
  { question: "Recoleta Cemetery está en La Boca.", answer: false },
  { question: "El Faro del Bicentenario está en Córdoba.", answer: true },
  { question: "El Obelisco fue inaugurado en el siglo XIX.", answer: false },
  { question: "La Catedral Metropolitana está cerca del Obelisco.", answer: true },
  { question: "El Monumento Belgrano se ubica en Belgrano, CABA.", answer: true },
  { question: "El Cementerio de Recoleta tiene tumbas famosas.", answer: true },
  { question: "La Casa Rosada está en Rosario.", answer: false },
  { question: "La bandera argentina se declaró nacional en el Monumento a la Bandera.", answer: false },
  { question: "La obra de Salamone incluye plazas y mataderos.", answer: true },
  { question: "San Ignacio Mini está en Misiones.", answer: true },
  { question: "El monumento a la bandera es patrimonio nacional.", answer: true },
  { question: "El Obelisco mide más de 70 metros.", answer: true },
  { question: "La Pirámide de Mayo es más antigua que el Obelisco.", answer: true },
  { question: "El Palacio Barolo fue construido en estilo art decó.", answer: true },
  { question: "El Cementerio Recoleta tiene la tumba de Evita.", answer: true },
  { question: "El Teatro Colón se inauguró en el año 1900.", answer: false },
  { question: "El Monumento a la Bandera se terminó en 1957.", answer: true },
  { question: "Córdoba capital no tiene monumentos históricos.", answer: false },
  { question: "La Casa Histórica de Tucumán fue declarada Patrimonio de la Humanidad.", answer: false },
  { question: "La Catedral Metropolitana fue escenario de asambleas históricas.", answer: true },
  { question: "Francisco Salamone era argentino.", answer: false },
  { question: "Recoleta Cemetery fue inaugurado en el siglo XIX.", answer: true },
];

export const conurbanoQuestions = [
  { question: "El conurbano bonaerense rodea la Ciudad de Buenos Aires.", answer: true },
  { question: "Lanús se encuentra al norte del conurbano.", answer: false },
  { question: "Quilmes es parte del área metropolitana.", answer: true },
  { question: "Tigre está en la provincia de Córdoba.", answer: false },
  { question: "Mar del Plata pertenece al conurbano.", answer: false },
  { question: "Avellaneda limita con La Boca.", answer: true },
  { question: "La línea Mitre llega al conurbano.", answer: true },
  { question: "Ezeiza está al norte del Riachuelo.", answer: false },
  { question: "San Isidro está en zona norte del conurbano.", answer: true },
  { question: "Morón tiene un estadio histórico.", answer: true },
  { question: "La universidad de Lomas de Zamora es cuturalmente relevante.", answer: true },
  { question: "Banfield está en provincia de La Pampa.", answer: false },
  { question: "José C. Paz está al oeste de la capital.", answer: true },
  { question: "San Fernando tiene islas en delta del Paraná.", answer: true },
  { question: "Ituzaingó está en la zona sur del conurbano.", answer: false },
  { question: "Fátima es un barrio del conurbano.", answer: false },
  { question: "La autopista Buenos Aires-La Plata cruza Quilmes.", answer: true },
  { question: "Pilar está al oeste de Buenos Aires capital.", answer: true },
  { question: "Merlo limita con La Matanza.", answer: true },
  { question: "Adrogué está al sur del Riachuelo.", answer: true },
  { question: "Morón es sede de clubes de fútbol famosos.", answer: true },
  { question: "La estación de tren en Temperley es parte del Roca.", answer: true },
  { question: "Lomas de Zamora limita con Lanús.", answer: true },
  { question: "El conurbano tiene playas oceánicas.", answer: false },
  { question: "La línea Sarmiento termina en Moreno.", answer: true },
  { question: "Tigre es famoso por su Puerto de Frutos.", answer: true },
  { question: "Quilmes es conocido por su cervecería histórica.", answer: true },
  { question: "General Pacheco está al sur del GBA.", answer: false },
  { question: "La campaña electoral bonaerense es relevante en el conurbano.", answer: true },
];
